config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get 'sessions/new'

  get '/', to: 'blogs#top'
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # /letter_openerのURLにアクセスした時、下記のようなメール送信BOXが出現
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validates :title, presence: true
  validates :content, length: { in: 1..140 }

  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  before_validation { email.downcase! }
  # ユーザーの値がバリデーション判定される前にemail属性を強制的に小文字に変換
  has_secure_password
  # セキュアにハッシュ化したパスワードを、データベース内のpassword_digestというカラムに保存する
  # 2つのペアの仮想的な属性 (passwordとpassword_confirmation) が使えるようになる。また、存在性と値が一致するかどうかのバリデーションも追加される
  # authenticateメソッドが使えるようになる (引数の文字列がパスワードと一致するとUserオブジェクトを、間違っているとfalseを返すメソッド) 。
  # has_secure_passwordメソッドを使用するためにはpassword_digestというカラムが必要
  validates :password, presence: true, length: { minimum: 6 }

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :set_user
  def set_user
    @user = current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :login_limit, only: [:new, :edit, :show, :destroy]
  before_action :set_limit, only: [:edit, :destroy]
  # before_action :set_user

  def index
    @blogs = Blog.all.reverse_order
    # @user = current_user
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id #現在ログインしているuserのidをblogのuser_idカラムに挿入する。
    if @blog.save
      ContactMailer.inform_mail(@blog).deliver
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to blogs_path, notice: "ツイートしました！"
    else
      # 入力フォームを再描画します。
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ツイートを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ツイートを削除しました！"
  end

  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id #現在ログインしているuserのidをblogのuser_idカラムに挿入する。
    # binding.pry
    render :new if @blog.invalid?
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content, :user_id, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  # def set_user
  #   @user = current_user
  # end

  # current_userが存在していなければ、強制的にログイン画面にリダイレクトさせる
  def login_limit
    if logged_in? == false
      redirect_to new_session_path, notice:"ログインしてください！"
    end
  end

  def set_limit
    unless current_user.id == @blog.user_id then
      redirect_to blog_path, notice:"あなたはこのツイートを編集できません！"
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)


      if @contact.save
        ContactMailer.contact_mail(@contact).deliver
        redirect_to @contact, notice: 'Contact was successfully created.'
        #format.json { render :show, status: :created, location: @contact }
      else
        render :new
        #format.json { render json: @contact.errors, status: :unprocessable_entity }
      end

  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # 送信されたメールアドレスを元に、find_byメソッドでデータベースからユーザを取り出し
    user = User.find_by(email: params[:session][:email].downcase)
    # パスワードが一致しているかを判定するためにはhas_secure_passwordが提供するauthenticateメソッドを使用
    if user && user.authenticate(params[:session][:password])
      # ログイン成功した場合
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      # ログイン失敗した場合
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites_blogs = @user.favorite_blogs
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    # @current_user || @current_user = User.find_by(id: session[:user_id])と同じ意味
    # @current_userが真の場合はそのままにし、偽の場合は右辺の値 User.find_by(id: session[:user_id]) を代入
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<% if @blog.errors.any? %>
  <div class="alert alert-danger" role="alert" id="error_explanation">
    <h3><%= @blog.errors.count %>件のエラーがあります。</h3>
    <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <div class="blog_title">
    <%= form.label :title %></br>
    <%= form.text_field :title, class: "text" %>
  </div>
  <div class="blog_title">
    <%= form.label :content %></br>
    <%= form.text_area :content, class: "text" %>
  </div>
  <div class="image">
    <%= form.label :image %>
    <!-- 確認画面から新規作成画面に戻った時に、 -->
    <!-- アップロードした画像を表示させるための記述 -->
    <%= image_tag(@blog.image.url) if @blog.image.url %>
    <%= form.file_field :image, id: :blog_image %>
    <!-- どのイメージか -->
  </div>
  <div class="actions margin">
    <%= form.submit %>
  </div>
<% end %>

<p><%= link_to '投稿一覧画面にもどる', blogs_path %></p>

app/views/blogs/confirm.html.erb
<h3 class="title1">以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <div class="margin"><%= image_tag(@blog.image) %></div>
  <div class="margin"><%= form.submit  "登録する" %></div>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2 class="title1">投稿を編集する</h2>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1 class="title1">投稿一覧</h1>
<div class="container">
  <!-- <p><%= notice %></p> -->
  <div class="row">
    <% @blogs.each_with_index do |blog, i| %>
      <% if i % 5 == 0 %>
        <div class="col-xs-12 col-sm-offset-1 col-sm-5 col-md-offset-1 col-md-3 panel panel-success">
      <% elsif i % 5 == 1 %>
        <div class="col-xs-12 col-sm-offset-1 col-sm-5 col-md-offset-1 col-md-3 panel panel-warning">
      <% elsif i % 5 == 2 %>
        <div class="col-xs-12 col-sm-offset-1 col-sm-5 col-md-offset-1 col-md-3 panel panel-info">
      <% elsif i % 5 == 3 %>
        <div class="col-xs-12 col-sm-offset-1 col-sm-5 col-md-offset-1 col-md-3 panel panel-danger">
      <% else %>
        <div class="col-xs-12 col-sm-offset-1 col-sm-5 col-md-offset-1 col-md-3 panel panel-default">
      <% end %>

        <div class="panel-heading">
          <%= blog.title %>
        </div>
        <div class="panel-body">
          <div class="scr">
            <p>
              <strong>投稿者:</strong>
              <%= blog.user.name %>
            </p>
            <p><%= blog.content %></p>

            <%= image_tag blog.image %>
          </div>
          <div class="blog-links">
            <%= link_to '詳細', blog_path(blog.id), class: 'btn btn-success' %>
            <% if logged_in? %>
              <% if blog.user_id == current_user.id%>
                <%= link_to "編集", edit_blog_path(blog.id), class: 'btn btn-warning', data: { confirm: '本当に編集していいですか？' } %>
                <%= link_to '削除', blog_path(blog.id), method: :delete, class: 'btn btn-danger', data: { confirm: '本当に削除していいですか？' } %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<h2 class="title1">投稿する</h2>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1 class="title1">投稿詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<% if @blog.image.url %>
  <div>
    <strong>画像:</strong>
    <%= image_tag @blog.image %>
  </div>
<% end %>

<div class="margin">
<% unless @blog.user_id == current_user.id %>
  <% if @favorite %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
</div>

<p><%= link_to '投稿一覧画面にもどる', blogs_path %></p>

app/views/blogs/top.html.erb
<div class="container">
<h1 class="title0">Share Posts</h1>
<h3>思いついた事をメモしよう</h3>
<%= image_tag 'twitterclone_icon.png', :width => '300'%>
<p>グループ内のメンバーにも知らせたいことを投稿しよう！</p>
<p>気になる投稿をお気に入りしよう！</p>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= form.label :name %></p>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <p><%= form.label :email %></p>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <p><%= form.label :content %></p>
    <%= form.text_area :content, id: :contact_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1 class="title1">Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1 class="title1">Message</h1>

<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share Posts</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li class="left"><%= link_to 'トップページ', "/" %></li>
        <li class="left"><%= link_to '投稿一覧', blogs_path %></li>
        <li class="left"><%= link_to 'メッセージ', new_contact_path %></li>

        <% if logged_in? %>
          <!-- ログインしている場合 -->
          <% if @user.image %>
            <li class="right"><%= image_tag @user.image, class: "image" %></li>
          <% else %>
            <li class="right"><%= image_tag 'twitterclone_icon.png', :width => '60' %></li>
          <% end %>
          <li class="label label-danger right"><%= link_to '投稿', new_blog_path %></li>
          <li class="label label-warning right"><%= link_to "プロフィール", user_path(current_user.id) %></li>
          <li class="label label-success right"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
        <% else %>
          <!-- ログインしていない場合 -->
          <li class="label label-warning right"><%= link_to "登録", new_user_path %></li>
          <li class="label label-success right"><%= link_to "ログイン", new_session_path %></li>
        <% end %>
      </ul>
    </header>
    <div class="container">
      <% flash.each do |key, value| %>
        <p><%= content_tag(:div, value, class: "#{key}") %></p>
      <% end %>

      <%= yield %>

    </div>
    <footer>
      <p>課題作成中</p>
      <p>© 2018 TwitterClone</p>
    </footer>

  </body>
</html>

app/views/users/new.html.erb
<h1 class="title1">Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="field">
    <p><%= f.label :name %></p>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <p><%= f.label :email %></p>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <p><%= f.label :password %></p>
    <%= f.password_field :password %></br>
  </div>
  <div class="field">
    <p><%= f.label :password_confirmation %></p>
    <%= f.password_field :password_confirmation %></br>
  </div>
  <div class="image">
    <p><%= f.label :image %></p>
    <%= f.file_field :image, id: :user_image %>
    <!-- id どのイメージか -->
  </div>
  <div class="margin">
    <%= f.submit "Create my account" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1 class="title1"><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>
<% if @user.image %>
  <p>アイコン画像:</p>
  <%= image_tag @user.image %>
<% end %>
<p>お気に入り:</p>
<div class="row">
  <% @favorites_blogs.each do |blog| %>
    <div class="col-xs-12 col-sm-offset-1 col-sm-5 col-md-offset-1 col-md-3 panel panel-success">
      <div class="panel-heading">
        <%= blog.title %>
      </div>
      <div class="panel-body">
        <%= blog.content %></div>
      <div class="blog-links">
        <%= link_to '詳細', blog_path(blog.id), class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
</div>
<% unless logged_in? %>
  <%= link_to "ログイン", new_session_path, class: 'btn btn-default' %>
<% end %>
<%= link_to "投稿一覧", blogs_path, class: 'btn btn-default' %>